preset: recommended
tab-width: 4
use-tabs: false
enabled:
  - long_array_syntax
  - strict
  - unalign_double_arrow
disabled:
  - align_double_arrow
  - short_array_syntax
finder:
  exclude:
    - "tests"
  name:
    - "*.php"